### ISSUE TITLE
点击接口详情，打开一个新的窗口，是否可在当前窗口跳转页面？

### ISSUE THREAD

**Issue by abeelan** [wuranxu/pity#102]
chrome 的标签页过多，体验有影响，内存开销也大。

**Comment by wuranxu** [comment]
> chrome 的标签页过多，体验有影响，内存开销也大。

是没有部署前端么？新版本实现了`多页签`，应该是新开窗口的，可以截图看看？

**Comment by abeelan** [comment]
> > chrome 的标签页过多，体验有影响，内存开销也大。
> 
> 是没有部署前端么？新版本实现了`多页签`，应该是新开窗口的，可以截图看看？

我的描述有误，本意是不想新开标签页，在原页面刷新即可。

**Comment by wuranxu** [comment]
> > > chrome 的标签页过多，体验有影响，内存开销也大。
> > 
> > 
> > 是没有部署前端么？新版本实现了`多页签`，应该是新开窗口的，可以截图看看？
> 
> 我的描述有误，本意是不想新开标签页，在原页面刷新即可。

参考下pity.fun的线上网站，应该是在同一个浏览器tab打开的多个页面。
