### ISSUE TITLE
docker-compose部署完注册报错了

### ISSUE THREAD

**Issue by cfy3133** [wuranxu/pity#103]
![image](https://user-images.githubusercontent.com/43978367/227778462-d82a49be-3345-4ebf-9b85-f91520619ce7.png)
是不是docker、docker-compose的版本太高了
![image](https://user-images.githubusercontent.com/43978367/227764394-f178511a-f334-4d30-abbf-84572f86e58f.png)
![image](https://user-images.githubusercontent.com/43978367/227764414-5de0efa0-9372-4ab2-9572-9f2de028bc28.png)

**Comment by wuranxu** [comment]
跟docker版本应该没关系，看起来是你没有自动`建库建表`，docker打镜像的时候估计还不支持自动建库，你可以连接docker的MySQL以后，创建db: pity，然后重新启动服务即可。

**Comment by cfy3133** [comment]
好的，谢谢您

**Comment by cfy3133** [comment]
好像表是建立了，但是还是不行
![image](https://user-images.githubusercontent.com/43978367/227870924-5f8a0b94-7459-40c4-84bd-c1ad395705af.png)

**Comment by wuranxu** [comment]
> 好像表是建立了，但是还是不行 ![image](https://user-images.githubusercontent.com/43978367/227870924-5f8a0b94-7459-40c4-84bd-c1ad395705af.png)

建议先别用docker部署了，那块我没测过。

**Comment by cfy3133** [comment]
好的
