### ISSUE TITLE
windows下载证书失败了

### ISSUE THREAD

**Issue by cfy3133** [wuranxu/pity#104]
![image](https://user-images.githubusercontent.com/43978367/227822257-b1c0e2ef-b54b-49e2-96f1-ed579ccbe415.png)

**Comment by wuranxu** [comment]
这个功能`暂时`关闭了，代理开启后经常CPU爆高。

**Comment by wuranxu** [comment]
> 这个功能`暂时`关闭了，代理开启后经常CPU爆高。

你可以本地配置打开proxy_on=True，在本地启动代理，接口会生效。

**Comment by cfy3133** [comment]
好的，谢谢您
