### ISSUE TITLE
请问作者啥时候更新一下docker部署？docker部署还是挺方便的

### ISSUE THREAD

**Issue by cfy3133** [wuranxu/pity#106]
请问作者啥时候更新一下docker部署？docker部署还是挺方便的

**Comment by wuranxu** [comment]
目前docker部署有什么问题么？之前是代码库没更新前端页面，目前已经更新好了

**Comment by cfy3133** [comment]
有问题的，部署之后，好像登录不了，试过了，之前问过您呢
![image](https://user-images.githubusercontent.com/43978367/229429342-3cd89fd6-ccd0-4369-8f30-327814392996.png)

**Comment by wuranxu** [comment]
> 有问题的，部署之后，好像登录不了，试过了，之前问过您呢 ![image](https://user-images.githubusercontent.com/43978367/229429342-3cd89fd6-ccd0-4369-8f30-327814392996.png)

这块有过改动，前端页面都是新的，能重新拉一下docker镜像吗？

**Comment by cfy3133** [comment]
我晚点再试一试，谢谢

**Comment by cfy3133** [comment]
您好，docker 部署成功了，但是访问地址后注册报错了
![image](https://user-images.githubusercontent.com/43978367/229966144-309508a5-8daf-4d7f-a232-b7be470ab967.png)

**Comment by cfy3133** [comment]
用例录制还是报错
![image](https://user-images.githubusercontent.com/43978367/229967604-e87acdf2-b490-49ff-ae4e-045b7a2e9cc8.png)

**Comment by wuranxu** [comment]
> 用例录制还是报错 ![image](https://user-images.githubusercontent.com/43978367/229967604-e87acdf2-b490-49ff-ae4e-045b7a2e9cc8.png)

MOCK_ON也要打开，注册页面的稍后我会更新

**Comment by wuranxu** [comment]
注册页面已更新~

**Comment by cfy3133** [comment]
好的，谢谢

**Comment by wuranxu** [comment]
> 好的，谢谢

突然想起来了代理那块抽出来了一个单独的py，docker估计没启动，后面我有空研究一下
