### ISSUE TITLE
下载证书还是失败

### ISSUE THREAD

**Issue by cfy3133** [wuranxu/pity#107]
![image](https://user-images.githubusercontent.com/43978367/230708131-b07f06fc-51e3-48a6-83f1-f7cdaec13fa7.png)
![image](https://user-images.githubusercontent.com/43978367/230708100-917bf5eb-49f4-462c-9b31-bcae369d8d43.png)
![image](https://user-images.githubusercontent.com/43978367/230708240-5d15fe0c-f1d4-4373-808d-77ebbbaf0f36.png)

**Comment by wuranxu** [comment]
docker启动问题，或者你可以直接本地python proxy.py启动这个代理服务

**Comment by cfy3133** [comment]
好的，谢谢！请问这个代理服务可以单独抽离出一个类似于谷歌的插件吗？这样方便很多呢

**Comment by wuranxu** [comment]
> 好的，谢谢！请问这个代理服务可以单独抽离出一个类似于谷歌的插件吗？这样方便很多呢

有其他人有类似的实现，实际上你们只需要生成har即可导入。

**Comment by cfy3133** [comment]
好像他们没有可以做到自动关联接口依赖参数的，没有作者您这个好用，哈哈
