### ISSUE TITLE
未添加过项目，点击接口测试菜单，点击添加项目，跳转后页面提示不存在！

### ISSUE THREAD

**Issue by feiwu999** [wuranxu/pity#109]
![image](https://user-images.githubusercontent.com/51976229/230718625-3265f723-67e9-4a9d-98d4-ee12dedda3a7.png)

![image](https://user-images.githubusercontent.com/51976229/230718636-45dccef4-3769-4e24-ba75-2879140821eb.png)

**Comment by wuranxu** [comment]
已修复~
