### ISSUE TITLE
更新到最新版本后又报错了

### ISSUE THREAD

**Issue by cfy3133** [wuranxu/pity#110]
![image](https://user-images.githubusercontent.com/43978367/231921175-152f7276-e229-41b3-ab34-302c21a0c75b.png)

**Comment by wuranxu** [comment]
![image](https://user-images.githubusercontent.com/11266738/231925791-0e9f3545-e081-437f-bccd-ab5a5adff698.png)
不知道 docker咋回事，目前来看是数据库没这个表，理论上来说会自动建表才对，docker不是我调试的，谨慎使用。

**Comment by cfy3133** [comment]
好的，好难，哈哈

**Comment by wuranxu** [comment]
> 好的，好难，哈哈

你可以连上你的docker mysql，看看数据表都在不在，大概率是不在的。

**Comment by cfy3133** [comment]
在的，我之前就看过，不知道为啥

**Comment by wuranxu** [comment]
> 在的，我之前就看过，不知道为啥

在的话不太可能会`报这种错`呀，你检查下数据库地址配置，然后debug试试

**Comment by cfy3133** [comment]
我删除docker容器后，再次docker-compose up又可以了，我之前就这样反反复复的，啥都没改，就有时候不可以，很奇怪的
