### ISSUE TITLE
请问为啥我用例录制，无法生成用例，按照用例录制的教程配置了

### ISSUE THREAD

**Issue by cfy3133** [wuranxu/pity#111]
![image](https://user-images.githubusercontent.com/43978367/232985745-e761a05a-4a4e-4663-934b-c3b05b25a857.png)

**Comment by wuranxu** [comment]
因为没有录制到数据，录制到数据这里会显示录制到的数据，此时数据为空。

检查下你的代理是否连接上，检查方式是浏览器打开: mitm.it

**Comment by cfy3133** [comment]
我看是正常的呢
![1681897757719](https://user-images.githubusercontent.com/43978367/233038446-356d46a8-54cf-4020-a3c9-9b95a8f2f80c.jpg)

**Comment by wuranxu** [comment]
1. 检查你是否访问了你要录制的地址
2. 可以刷新一下此页面，防止录制到的数据未写入

**Comment by cfy3133** [comment]
刷新啥的都试过了，看起来一切正常，地址也是对的，就是录制不上，太难了

**Comment by wuranxu** [comment]
现在问题是没有录制到，还是录制到了点击不了?我这块没改过，大概率是可以用的，我现在本地试一下

**Comment by cfy3133** [comment]
是没有录制到，但是我的网页也是正常的，代理也是正常开启了，但是就是录制不到。好的，麻烦了

**Comment by wuranxu** [comment]
可以录制到，你检查下吧
- 1. 开启mock和proxy配置
- 2. 启动proxy.py
- 3. 启动pity.py
- 4. 启动代理
- 5. 开始录制，如果没获取到录制的数据，刷新下页面

![image](https://user-images.githubusercontent.com/11266738/233286484-9310880c-3ecd-42d6-a25b-46231b53a041.png)

**Comment by wuranxu** [comment]
> 是没有录制到，但是我的网页也是正常的，代理也是正常开启了，但是就是录制不到。好的，麻烦了

记得证书也要下载并安装

**Comment by cfy3133** [comment]
v5sit-micro.51qqt.com录制的地址是这个，难道是地址有问题，导致录制不了吗

**Comment by cfy3133** [comment]
果然我用您的地址是可以的，我用我的地址就是不行
![image](https://user-images.githubusercontent.com/43978367/233292053-f7880329-6e63-4db4-92bb-9f97fccfdf47.png)
感觉是个bug吧

**Comment by cfy3133** [comment]
我的地址就是无法录制上
![image](https://user-images.githubusercontent.com/43978367/233292322-736a7587-3845-4969-8638-eb2c685a4373.png)

**Comment by cfy3133** [comment]
是不是有-解析不了，特殊的字符的处理问题？

**Comment by wuranxu** [comment]
> 我的地址就是无法录制上 ![image](https://user-images.githubusercontent.com/43978367/233292322-736a7587-3845-4969-8638-eb2c685a4373.png)

这是你自己的问题，首先，你可以使用一个很简单的网站，比如像我刚才的leetcode.cn，看是否能录制上，其次，如果你觉得是-的问题。在正则表达式里面`-`确实是特殊字符，我这个输入框为了能匹配url，必然不会是简单的文本匹配，所以建议你先确认到底是录制不到，还是`-`的问题，如果是`-`的问题，我建议你搜索一下正则表达式，而不是说`太难了，录制不上`这样的话。
首先我也是在很耐心的帮你解决问题，希望你也能耐心点去排查问题，毕竟我这边0改动也经过测试了，有问题我协助你，少点抱怨吧，对于没有问题的功能点，我想我不会再花更多时间去排查了。

**Comment by cfy3133** [comment]
好的，谢谢您，我先看下怎么匹配
