### ISSUE TITLE
测试用例里面添加的都是单接口用例吗？

### ISSUE THREAD

**Issue by tahitimoon** [wuranxu/pity#112]
找了好久没找到，怎么使用多个api接口组成场景用例，测试用例里面添加的都是单接口用例吗？

**Comment by wuranxu** [comment]
[参考文档](https://wuranxu.github.io/pityDoc/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B/%E6%8E%A5%E5%8F%A3%E4%BE%9D%E8%B5%96)

场景用例的话，先拆分成一个个步骤用例，用前置条件关联起来
比如你的场景是 A->B->C

那么你的主体用例就是C，A和B作为C的前置用例
