### ISSUE TITLE
接口用例列表，选择2个或者多个用例查看详情后，再次选择一个用例查看详情，详情页面展示的用例详情数据不正确！

### ISSUE THREAD

**Issue by feiwu999** [wuranxu/pity#113]
接口用例列表，选择2个或者多个用例查看详情后，再次选择一个用例查看详情，详情页面展示的用例详情数据不正确！
正常来说一个是登录的，一个是查询环境列表的，但目前看浏览器url不一样，返回的都变成同一个用例详情
![image](https://user-images.githubusercontent.com/51976229/236505124-a7a53428-8f89-4312-9ec2-32d3397f4a36.png)

![image](https://user-images.githubusercontent.com/51976229/236505305-9d4304a7-e0d7-4bc8-9cc9-2bbe115196de.png)
![image](https://user-images.githubusercontent.com/51976229/236505378-2ea383a7-25e5-4e5c-a633-549c88f40931.png)

**Comment by wuranxu** [comment]
应该是多页签的问题，可以刷新下页面，暂时我没法解决这个
