### ISSUE TITLE
测试报告详情页面，饼状图上面的成功数量不正确

### ISSUE THREAD

**Issue by feiwu999** [wuranxu/pity#115]
![image](https://user-images.githubusercontent.com/51976229/236515016-fdd8ce8f-31f5-4a5a-8ec9-a7887920281d.png)

好像我理解错了，这个1是百分比的意思，个人认为这里展示百分比或者成功的数量是否更加友好一些呢？

**Comment by wuranxu** [comment]
好的，回头我确认一下

**Comment by wuranxu** [comment]
> 好的，回头我确认一下

已加上百分比，默认的数据不好修改，没找到对应api
