### ISSUE TITLE
python 3.9的报错

### ISSUE THREAD

**Issue by llaichiyu** [wuranxu/pity#117]
curl 'http://192.168.7.82:7777/testcase/plan/update' \
  -H 'Accept: application/json' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://192.168.7.82:7777' \
  -H 'Referer: http://192.168.7.82:7777/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODc4Mjg1OTEsImlkIjoxLCJ1c2VybmFtZSI6InBhdWxpbmUiLCJuYW1lIjoicGF1bGluZSIsImVtYWlsIjoiMzAyODY5OTA3QHFxLmNvbSIsInJvbGUiOjIsInBob25lIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyMy0wNi0yMCAxMDo0MTowMyIsInVwZGF0ZWRfYXQiOiIyMDIzLTA2LTIwIDEwOjQxOjAzIiwiZGVsZXRlZF9hdCI6MCwidXBkYXRlX3VzZXIiOm51bGwsImxhc3RfbG9naW5fYXQiOiIyMDIzLTA2LTI0IDA5OjE2OjMxIiwiYXZhdGFyIjpudWxsLCJpc192YWxpZCI6dHJ1ZX0.Z-hlBrwL-vBt8037YaYceHsxWecjOvfYESQI4hmv7U0' \
  --data-raw '{"name":"plan0","env":[1],"priority":"P0","cron":"0 0 8 * 0","ordered":true,"case_list":[3,4],"project_id":2,"pass_rate":100,"retry_minutes":0,"msg_type":["0"],"receiver":[1],"id":1}' \
  --compressed \
  --insecure

【返回】

{code: 110, msg: "'zoneinfo.ZoneInfo' object has no attribute 'normalize'", data: null}

【预期】
是否回退python3.8

**Comment by wuranxu** [comment]
应该是和apscheduler有关，可以关注下它的版本
