### ISSUE TITLE
通过websocket实时发送录制数据给前端，楼主怎么注释啦，现在通过刷新页面调用@router.get("/record/status", summary="获取录制接口请求状态")接口，才能获取录制的接口？

### ISSUE THREAD

**Issue by tahitimoon** [wuranxu/pity#120]
通过websocket实时发送录制数据给前端，楼主怎么注释啦，现在通过刷新页面调用@router.get("/record/status", summary="获取录制接口请求状态")接口，才能获取录制的接口？

**Comment by wuranxu** [comment]
此功能暂时下线，后续再考虑更优办法。
