### ISSUE TITLE
docker打包后的容器访问地址找不到

### ISSUE THREAD

**Issue by InnSea** [wuranxu/pity#122]
![image](https://github.com/wuranxu/pity/assets/130050263/c489cd2b-23f2-400a-b615-d752470f5dce)

**Comment by firmlybelieve** [comment]
最新版本启动报错了
![image](https://github.com/wuranxu/pity/assets/4637787/57cebf6a-6026-4092-a02c-a4a44a3f3a21)

**Comment by wuranxu** [comment]
docker应该无问题，有问题可以自己排查
