### ISSUE TITLE
断言接口返回码失败

### ISSUE THREAD

**Issue by InnSea** [wuranxu/pity#125]
![image](https://github.com/wuranxu/pity/assets/130050263/486ce01b-40f9-49aa-94a8-dd4b9a481f84)
![image](https://github.com/wuranxu/pity/assets/130050263/6f23114b-4a04-47e6-ae87-c3d691c00cae)
![image](https://github.com/wuranxu/pity/assets/130050263/515b9737-0478-4666-9fe4-75a87ab438de)

接口码返回为200，但是断言失败了？

**Comment by InnSea** [comment]
断言语句也没问题

**Comment by InnSea** [comment]
<img width="590" alt="image" src="https://github.com/wuranxu/pity/assets/130050263/a3015b5c-503c-4bb0-8913-043a2470ca1d">
 这里的判断是不是有问题？直接吧预期结果和实际结果比较了，似乎没有从返回数据里提取参数？

**Comment by wuranxu** [comment]
> <img alt="image" width="590" src="https://private-user-images.githubusercontent.com/130050263/289034812-a3015b5c-503c-4bb0-8913-043a2470ca1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTk0OTEsIm5iZiI6MTcwNjU5OTE5MSwicGF0aCI6Ii8xMzAwNTAyNjMvMjg5MDM0ODEyLWEzMDE1YjVjLTUwM2MtNGJiMC04OTEzLTA0M2EyNDcwY2ExZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwNzE5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Yjg2NzkyMzIxYWIwZTM1YjI0ZDVjYzJmYWRkMjkzMzc4ODQzMGNmZjg2NDBlMTU3YzRlZWE2YmQ1YjZkMTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H3CwVwxIKV3B3RmJ5K5oDyf9l11SExiL2bNpOwTp0UY"> 这里的判断是不是有问题？直接吧预期结果和实际结果比较了，似乎没有从返回数据里提取参数？

这里已经进行了改动，目前统一使用`参数提取`去操作用例中的变量，不再提供默认response作为用例返回值的功能。
