### ISSUE TITLE
发送通知notice方法有一个问题会导致发送邮件失败

### ISSUE THREAD

**Issue by InnSea** [wuranxu/pity#129]
使用users重复变量名会导致问题
![image](https://github.com/wuranxu/pity/assets/130050263/1ab867b1-f25e-4b53-9463-b606f579383d)
<img width="1067" alt="image" src="https://github.com/wuranxu/pity/assets/130050263/364f1afd-1684-4d07-a438-25e0c317468b">

**Comment by wuranxu** [comment]
是用了email+dingding的推送方式，然后dingding还在第一个选项对吧，好的，我修复一下

**Comment by InnSea** [comment]
是的
