### ISSUE TITLE
对于提取出来的数据，类型不一致该怎么办呢？

### ISSUE THREAD

**Issue by InnSea** [wuranxu/pity#132]
![image](https://github.com/wuranxu/pity/assets/130050263/06bc525d-5f37-42a7-b4bd-94915fa80df1)
![image](https://github.com/wuranxu/pity/assets/130050263/ab3fddd9-52cf-4198-beff-31130edf816f)

**Comment by InnSea** [comment]
都转成str类型可行吗？

**Comment by wuranxu** [comment]
已使用新逻辑

**Comment by InnSea** [comment]
看到最近好像更新了不少代码，会出新的教程嘛？

**Comment by wuranxu** [comment]
> 看到最近好像更新了不少代码，会出新的教程嘛？

大概率没时间写了，能完成功能已经很费时间了。

**Comment by InnSea** [comment]
用法上变动大吗？
