### ISSUE TITLE
【BUG】工作台最近一周创建用例树统计数据处理有问题：count始终都是1，query_weekly_user_casef方法里ans[date.strftime("%Y-%m-%d")] = count应该是有问题的，尝试修复了一下没问题了

### ISSUE THREAD

**Issue by InnSea** [wuranxu/pity#135]
![image](https://github.com/wuranxu/pity/assets/130050263/fb4ecf38-9bd8-4bbe-9f50-9b171759453a)

**Comment by InnSea** [comment]
原逻辑：
![image](https://github.com/wuranxu/pity/assets/130050263/f1f14a0a-367d-4982-8386-1dd2064b1ff1)

**Comment by wuranxu** [comment]
fixed
