### ISSUE TITLE
bug列表

### ISSUE THREAD

**Issue by wuranxu** [wuranxu/pity#40]
😭 由于bug太多，所以都提到这里来吧。

**Comment by wuranxu** [comment]
- [ ] 前端会莫名其妙重定向到登录页（明明token还在）

**Comment by wuranxu** [comment]
- 接口返回报错

<img width="1552" alt="833c99d6677d5e2c0cbee2dfb395ec8" src="https://user-images.githubusercontent.com/11266738/156485298-2b56f0b2-17c3-449b-af23-e14cc1df6ee5.png">

**Comment by wuranxu** [comment]
#### 非常严重的bug

🐛  `/testcase/tree`接口无法获取到具体的用例，导致测试计划无法选中case

**Comment by wuranxu** [comment]
token过期/失效的时候，重定向的url套了2层redirect

**Comment by wuranxu** [comment]
> by fangchat

工作台统计用例数据不准确，实际只能统计6天的数据

**Comment by wuranxu** [comment]
> #### 非常严重的bug
> 🐛 `/testcase/tree`接口无法获取到具体的用例，导致测试计划无法选中case

fixed，获取子目录时，传入的都是父目录id引起。同时修复了根目录case无法获取的问题。

**Comment by wuranxu** [comment]
### 测试计划
- [ ] 选取测试计划case的时候偶尔会报错，split相关
- [ ] 工作台统计用例数据不准确，实际只能统计6天的数据
- [ ] token过期/失效的时候，重定向的url套了2层redirect

**Comment by luojun0115** [comment]
### 操作步骤：
1. 添加一条断言
2. 再添加一条

### 预期结果：
界面上有2条断言
### 实际结果：
第2条会覆盖第1条的。

**Comment by luojun0115** [comment]
## 断言问题

### 操作步骤：
1. 添加一条断言
2. 再添加一条

### 预期结果：
界面上有2条断言
### 实际结果：
第2条会覆盖第1条的。

**Comment by wuranxu** [comment]
项目描述太长的时候，页面显示不正常

**Comment by wuranxu** [comment]
> 项目描述太长的时候，页面显示不正常

fixed

**Comment by luojun0115** [comment]
> ## 断言问题
> ### 操作步骤：
> 1. 添加一条断言
> 2. 再添加一条
> 
> ### 预期结果：
> 界面上有2条断言
> 
> ### 实际结果：
> 第2条会覆盖第1条的。

现在正常了，以后遇到再说吧

**Comment by wuranxu** [comment]
> > ## 断言问题
> > ### 操作步骤：
> > 
> > 1. 添加一条断言
> > 2. 再添加一条
> > 
> > ### 预期结果：
> > 界面上有2条断言
> > ### 实际结果：
> > 第2条会覆盖第1条的。
> 
> 现在正常了，以后遇到再说吧

已修复，感谢龙哥。

**Comment by mijiawei** [comment]
添加测试用例目录无法正常加载（http://localhost:7777/#/apiTest/testcase）

操作步骤：
点击添加按钮，添加测试用例目录
确认数据库该数据被成功添加
刷新页面，报错缺少参数:move

![screenshot-20220320-191425](https://user-images.githubusercontent.com/17823529/159159708-ca264170-9da8-431b-8269-28ae07f60040.png)

**Comment by wuranxu** [comment]
> 添加测试用例目录无法正常加载（[http://localhost:7777/#/apiTest/testcase）](http://localhost:7777/#/apiTest/testcase%EF%BC%89)
> 
> 操作步骤： 点击添加按钮，添加测试用例目录 确认数据库该数据被成功添加 刷新页面，报错缺少参数:move
> 
> ![screenshot-20220320-191425](https://user-images.githubusercontent.com/17823529/159159708-ca264170-9da8-431b-8269-28ae07f60040.png)
> 
> 前端代码是旧的导致，我这边后端设置一下默认值。

已修复

**Comment by mijiawei** [comment]
/config/address/list 这个接口404了

**Comment by wuranxu** [comment]
> /config/address/list 这个接口404了

测试代码，后端还未开发，不用管。

**Comment by wuranxu** [comment]
- [ ] 网关地址需要以wss/ws/http/https开头，防止乱输入的情况
- [ ] base_path缓存更新时未删除的bug
- [ ] bash_path用send按钮请求的时候未生效
