### ISSUE TITLE
添加用例和查看详情每次都打开新的窗口

### ISSUE THREAD

**Issue by feiwu999** [wuranxu/pity#44]
![image](https://user-images.githubusercontent.com/51976229/157713991-9d5a542d-cb86-49e6-81df-8eab1c800070.png)
添加用例和查看详情每次都打开新的窗口，新增多个案例，窗口导致太多，不友好，个人建议在当前页面显示更好一点。

**Comment by wuranxu** [comment]
目前用的框架不支持，暂时不会做改变，除非底层框架支持标签页。
