### ISSUE TITLE
用例列表如何快速查找到测试报告里面的某一条用例？

### ISSUE THREAD

**Issue by feiwu999** [wuranxu/pity#45]
今天看测试报告里面的用例，想去查找这条用例在哪里，有点费时，
![image](https://user-images.githubusercontent.com/51976229/157795938-3ec64661-7c9c-4aae-8615-10355fa092c4.png)
![image](https://user-images.githubusercontent.com/51976229/157796089-2f1da5fc-abcb-4520-8534-4095f32c5859.png)

**Comment by wuranxu** [comment]
可以，我也注意到这个问题了，之后会完成这个功能。
