### ISSUE TITLE
关于用例执行详情日志记录展示一些小建议

### ISSUE THREAD

**Issue by feiwu999** [wuranxu/pity#46]
这里的日志一直在叠加，随着测试场景增加，后面看某个场景的执行日志有些麻烦，是否优化为点击对应的场景，只展示各自的执行日志记录？
![image](https://user-images.githubusercontent.com/51976229/157823164-3e2b185a-ae5e-41ff-b878-975c9b1178ab.png)
![image](https://user-images.githubusercontent.com/51976229/157823486-4055ca5e-79f4-4d88-a9cd-d76b8b07abcd.png)

**Comment by wuranxu** [comment]
这样看确实会比较复杂，后续日志可能会改动。
`目前的话`可以通过搜索日志达到一样的效果。
