### ISSUE TITLE
前置条件-缺少参数value

### ISSUE THREAD

**Issue by feiwu999** [wuranxu/pity#47]
![image](https://user-images.githubusercontent.com/51976229/157834300-bc59cbfd-1541-442a-8390-4ae20b879554.png)

这里的返回值好些必填，或者‘’，感觉 应该必填，不然怎么取到这个返回值呢？

另外个人小建议：
如果脚本里面导入某个库，但是没有安装或提示找不到，是否后台可以对这种情况处理，自动安装缺少的库，不然添加的脚本可能无法运行
脚本里面放入pip install xxx  貌似也不行

**Comment by wuranxu** [comment]
返回值不是`必填`的原因：有的前后置条件只是需要执行一下，比如time.sleep，这种是可以不需要返回值的。至于图中的缺少value，应该是个bug。

对于缺少的库，这个目前没有很好的解决办法，就算提供了`在线安装`包的功能，在容器/发布系统等机器启动时也会报错，不过这个功能确实得支持。

**Comment by feiwu999** [comment]
好的，感谢洛哥解答！
