### ISSUE TITLE
用例列表-小优化建议

### ISSUE THREAD

**Issue by feiwu999** [wuranxu/pity#48]
1、笔记本100%比例的时候，这里展示不全，也不好进行切换下一页？
2、用例列表的排序，是否按照case_id排序友好一些？
3、移动用例到某个目录好多选择不了？
![image](https://user-images.githubusercontent.com/51976229/157853922-b419d9b6-1493-4efc-80c0-70b86f095fd2.png)

![image](https://user-images.githubusercontent.com/51976229/157901772-8ac8aba0-e7f5-4fce-a96a-e83a5cc81385.png)

**Comment by wuranxu** [comment]
1. 是个bug，需要修复 感谢提出
2. 应该是按照创建时间排序的，这个可以加个排序功能
3. 也是bug，与测试计划选择case出现的冲突，`感谢指出`。

**Comment by feiwu999** [comment]
其他问题已经修复，现在有2个小问题，
1.A目录案例，移动到A目录下面的子目录，移动成功，但是A目录还是可以看到用例
2.多层级目录的时候，移动目录无法选择多层级下的目录

![image](https://user-images.githubusercontent.com/51976229/158139037-7e3440a3-9c33-4aab-8caa-a7ca78a64982.png)
![image](https://user-images.githubusercontent.com/51976229/158139196-6a3f85cb-1cac-4e9b-b4fe-23c74f4d5385.png)

**Comment by wuranxu** [comment]
已修复。
