### ISSUE TITLE
关于构造器及数据库配置的小建议

### ISSUE THREAD

**Issue by feiwu999** [wuranxu/pity#49]
1、数据库配置建议增加一列-数据库名，
2、用例执行成功如何断言数据库是否存在记录或者更新成功
3、数据库配置名称更新后，用例详情前后置条件构造器中数据库名称未更新，导致获取数据库配置失败
4、假如前后置构造器中SQL类型选择的是SIT环境的一个数据库，但是后面我选择UAT环境执行案例，由于是通过env+name去获取DB连接信息，不同环境的数据库配置名称可能不一样，导致可能获取不到配置而失败。目前想随时切换不同环境执行，只能把配置名称配成一样，这个点看看洛哥能否有好的优化办法。

![image](https://user-images.githubusercontent.com/51976229/158010457-edd1b876-fe7d-48be-8b11-c83429dfbf79.png)

![1647073057(1)](https://user-images.githubusercontent.com/51976229/158010494-5ff6c590-b787-47c6-8950-f0380cbed013.jpg)

![image](https://user-images.githubusercontent.com/51976229/158010578-6776432d-234d-4059-a94b-cc57f4fc776a.png)
![image](https://user-images.githubusercontent.com/51976229/158010631-04138122-9302-4112-811b-1c9651d8b143.png)
![image](https://user-images.githubusercontent.com/51976229/158011043-e6b23fe5-af68-4df7-9920-2b3f6b3af9e7.png)

**Comment by wuranxu** [comment]
> 1、数据库配置建议增加一列-数据库名， 2、用例执行成功如何断言数据库是否存在记录或者更新成功 3、数据库配置名称更新后，用例详情前后置条件构造器中数据库名称未更新，导致获取数据库配置失败 4、假如前后置构造器中SQL类型选择的是SIT环境的一个数据库，但是后面我选择UAT环境执行案例，由于是通过env+name去获取DB连接信息，不同环境的数据库配置名称可能不一样，导致可能获取不到配置而失败。目前想随时切换不同环境执行，只能把配置名称配成一样，这个点看看洛哥能否有好的优化办法。
> 
> ![image](https://user-images.githubusercontent.com/51976229/158010457-edd1b876-fe7d-48be-8b11-c83429dfbf79.png)
> 
> ![1647073057(1)](https://user-images.githubusercontent.com/51976229/158010494-5ff6c590-b787-47c6-8950-f0380cbed013.jpg)
> 
> ![image](https://user-images.githubusercontent.com/51976229/158010578-6776432d-234d-4059-a94b-cc57f4fc776a.png) ![image](https://user-images.githubusercontent.com/51976229/158010631-04138122-9302-4112-811b-1c9651d8b143.png) ![image](https://user-images.githubusercontent.com/51976229/158011043-e6b23fe5-af68-4df7-9920-2b3f6b3af9e7.png)

1. 可以支持
2. 需要编写后置条件，去查询sql里面有没有更新/新增的数据，一般是select最新的数据库值，接着根据你传入的参数做断言
3. 没有这么智能，更新数据库名称不会触发`修改用例数据库`的功能。 
4. 数据库理论上来说应该是根据环境+数据库名称（你定义的）来决定具体的连接，所以如果存在不同环境database不一致的情况，也是没关系的，如果现在不能用，那可能是有问题。所以你的数据库名称就不应该再戴上环境名称了，而应该叫`订单数据库`或者`XXX`，而不应该带上环境的标识，通过环境+名称（你定义的）来确定我在A环境的时候能够调用到正确的数据库。

- 后续可以做多环境数据库名称校验的功能，为了方便用例适配多环境，所以数据库不能固定，比如A环境下怎么知道连A数据库，B环境怎么知道连B数据库，只能通过名称来判断。保持住名称统一，切换环境也能读到对应的数据库。

**Comment by wuranxu** [comment]
需求一已完成。

**Comment by feiwu999** [comment]
好的，谢谢洛哥，关于第二点还有点小疑问，断言在后置条件之前执行，所以我断言的时候用到了后置条件变量，会返回None,导致断言不通过。

![image](https://user-images.githubusercontent.com/51976229/158028170-35ea6282-8dc5-4ccc-aa5b-1eb500c9eb40.png)

**Comment by wuranxu** [comment]
> 好的，谢谢洛哥，关于第二点还有点小疑问，断言在后置条件之前执行，所以我断言的时候用到了后置条件变量，会返回None,导致断言不通过。
> 
> ![image](https://user-images.githubusercontent.com/51976229/158028170-35ea6282-8dc5-4ccc-aa5b-1eb500c9eb40.png)

好的，会调整`断言`和`后置条件`的顺序，解决这个问题。

目前是先断言，后执行后置条件，现在改为:

前置=>接口请求=>后置=>断言
