### ISSUE TITLE
测试计划和用户管理页面小优化

### ISSUE THREAD

**Issue by feiwu999** [wuranxu/pity#50]
1、私有项目，项目列表看不见，但是测试计划还是可以展现，并且跳转到私有项目详情页面，预期应该看不到私有项目的计划

![image](https://user-images.githubusercontent.com/51976229/158027575-7cd0805c-6ee2-4cba-a4e7-592e8fba4c0a.png)

![image](https://user-images.githubusercontent.com/51976229/158027538-3e9ca6a8-4ceb-44c4-8621-63184cbbc129.png)
![image](https://user-images.githubusercontent.com/51976229/158027605-2f99095b-452d-44c8-9e7a-9038878693f4.png)

2、
![image](https://user-images.githubusercontent.com/51976229/158027819-42f04b1b-ac86-46ae-8817-b62b67c32050.png)

**Comment by wuranxu** [comment]
好的 感谢！ 明天仔细看看

**Comment by wuranxu** [comment]
测试计划中应该看不见对应项目了，页面的权限还没加上。太晚了，可能还有bug

**Comment by wuranxu** [comment]
问题2已经改成 只有超级管理员可以看到此页面了。

**Comment by wuranxu** [comment]
fixed
