### ISSUE TITLE
不同的项目添加相同的用例名称，用例添加失败

### ISSUE THREAD

**Issue by feiwu999** [wuranxu/pity#51]
1、假如有ABC三个项目，每个项目都有登录的功能案例，这种情况应该要支持，用例名称不能唯一

![image](https://user-images.githubusercontent.com/51976229/158047517-29364e87-3e05-4afb-bd1b-0a1810e397b1.png)
![image](https://user-images.githubusercontent.com/51976229/158048508-7f5877be-60f8-4866-a1dd-ff27450670b1.png)

2、切换项目，用例列表未更新
![image](https://user-images.githubusercontent.com/51976229/158048462-b3c37412-d171-4f25-9fb7-beae4685d292.png)

**Comment by wuranxu** [comment]
收到，这属于早期设计，后续会根据项目+目录+用例名来判断唯一性。

**Comment by feiwu999** [comment]
好的，期待更加完美的设计！

**Comment by wuranxu** [comment]
> 好的，期待更加完美的设计！

已调整，执行下以下sql:

```sql
drop index ix_test_case_name on pity_testcase;

create unique index ix_test_case_name
	on pity_testcase (directory_id, name);

```

**Comment by wuranxu** [comment]
问题1 2都已修复~
1. 需要上述sql
2. 切换项目会变更右侧内容
