### ISSUE TITLE
新建测试用例，添加请求参数body(from-data)时，前端报错

### ISSUE THREAD

**Issue by azdwa** [wuranxu/pity#55]
新建测试用例，添加请求参数body(from-data)，点add 按钮，前端报错
![image](https://user-images.githubusercontent.com/16831065/164010826-d79be8bf-9cba-4aba-afcb-f13a1568fd4e.png)

**Comment by wuranxu** [comment]
> 新建测试用例，添加请求参数body(from-data)，点add 按钮，前端报错 ![image](https://user-images.githubusercontent.com/16831065/164010826-d79be8bf-9cba-4aba-afcb-f13a1568fd4e.png)

收到，这个页面后面会重做，与编辑页面保持一致。
