### ISSUE TITLE
执行delete语句未对数据表数据进行删除操作

### ISSUE THREAD

**Issue by xiaoermeng** [wuranxu/pity#58]
接口前置以及后置、SQL客户端处执行SQL删除操作，实际未能成功删除测试数据
![image](https://user-images.githubusercontent.com/39907144/166470169-289072cc-12be-4e4c-b83a-0ae7ff5f454c.png)

**Comment by xiaoermeng** [comment]
![image](https://user-images.githubusercontent.com/39907144/166471050-34561107-1a28-4b8f-9064-ebbc6f605292.png)

**Comment by wuranxu** [comment]
ok 我看看

**Comment by wuranxu** [comment]
已修复
