### ISSUE TITLE
平台不能显示普通用户信息

### ISSUE THREAD

**Issue by xiaoermeng** [wuranxu/pity#62]
新增普通用户，使用管理员账号进行用户管理，不能展示其它用户信息，数据库中有数据
![image](https://user-images.githubusercontent.com/39907144/167244260-ed8fa0ec-703b-4dd5-8ccd-e4ceb904f198.png)
![image](https://user-images.githubusercontent.com/39907144/167244284-d87dc8d0-7752-44e6-86a6-42a550a7eb6a.png)
![image](https://user-images.githubusercontent.com/39907144/167244303-8127976b-7cc7-4819-a13f-2f88d3a04830.png)

**Comment by wuranxu** [comment]
缓存问题，后续一起解决。

**Comment by wuranxu** [comment]
应该ok了
