### ISSUE TITLE
用例断言未执行实际结果为必填选项，使用${}无法调用全局变量（可能调用方式不对）

### ISSUE THREAD

**Issue by qwerdome** [wuranxu/pity#63]
![image](https://user-images.githubusercontent.com/74087938/167823470-e209e53c-8ee1-4300-aad8-db13a56cf653.png)

**Comment by wuranxu** [comment]
没太明白必填选项是啥意思，或者说有什么不妥的地方。
全局变量如果用不了，可以检查一下是否和你执行用例的`环境`是匹配的，如果匹配的话还用不了，请贴出对应的日志

**Comment by wuranxu** [comment]
未回复，关闭issue
