### ISSUE TITLE
接口断言取值失败

### ISSUE THREAD

**Issue by xiaoermeng** [wuranxu/pity#66]
预期结果放的是相应报文，之前的版本断言没问题，新版本的断言失败
![image](https://user-images.githubusercontent.com/39907144/170904281-aa8da885-c350-4fbb-90d8-d0292a85a25b.png)
![image](https://user-images.githubusercontent.com/39907144/170904323-b4bc780b-03ff-4c49-b4e6-09202eef2fe7.png)

**Comment by wuranxu** [comment]
断言有一定的调整，可以参考下`出参规则`，新版本使用体验比目前更明确一些。
