### ISSUE TITLE
保存用例提示{缺少参数: priority}

### ISSUE THREAD

**Issue by xiaoermeng** [wuranxu/pity#67]
![image](https://user-images.githubusercontent.com/39907144/171319258-f0c9ca8a-f97e-4b72-88eb-9d5a75f2f329.png)

**Comment by wuranxu** [comment]
你这个是回到了`旧版本`吗？页面不是新的

**Comment by xiaoermeng** [comment]
已使用更新的前端代码，未出现此问题。
