### ISSUE TITLE
用例执行成功，日志提示{name 'ans' is not defined}

### ISSUE THREAD

**Issue by xiaoermeng** [wuranxu/pity#68]
![image](https://user-images.githubusercontent.com/39907144/171319369-df3484aa-d0c5-4d22-8968-ee76abd5d0fa.png)

**Comment by wuranxu** [comment]
确保一下代码最新吧，前端代码也需要最新。

**Comment by xiaoermeng** [comment]
使用更新的前端代码依旧存在该问题

**Comment by wuranxu** [comment]
> 使用更新的前端代码依旧存在该问题

好的，我抽空修复下。

**Comment by wuranxu** [comment]
已解决，变量名更换问题，拉下最新代码即可。
