### ISSUE TITLE
定时任务执行失败

### ISSUE THREAD

**Issue by huangxun201314** [wuranxu/pity#81]
测试计划可以手动执行，定时任务自动执行时出错。
`\lib\asyncio\base_events.py:1787: RuntimeWarning: coroutine 'Executor.run_test_plan' was never awaited
  handle = None  # Needed to break cycles when an exception occurs.
RuntimeWarning: Enable tracemalloc to get the object allocation traceback`

**Comment by wuranxu** [comment]
fixed
