### ISSUE TITLE
SQL客户端加载多环境下对局哭多个表的时候响应很慢，有没有办法提升一下性能？

### ISSUE THREAD

**Issue by feiwu999** [wuranxu/pity#82]

**Comment by wuranxu** [comment]
第一次的时候会比较慢，特别是环境多了以后。目前已经加入`缓存`了，第二次加载会比较快。
要优化的话，需要等用户点击对应的连接以后才展示对应的表字段。

**Comment by feiwu999** [comment]
嗯，好的，后续有空的话，期待洛哥的优化，毕竟一般现在项目都是多环境多库多表的，

**Comment by wuranxu** [comment]
> 嗯，好的，后续有空的话，期待洛哥的优化，毕竟一般现在项目都是多环境多库多表的，

已优化，可以拉下最新代码尝试，前后端都需要更新。
