### ISSUE TITLE
断言结果显示不准确。断言失败的测试结果依旧显示成功

### ISSUE THREAD

**Issue by youngtester** [wuranxu/pity#87]
![image](https://user-images.githubusercontent.com/13212775/188151805-2fa5e999-29cc-4a31-88c9-faee278e397e.png)
这快如果断言失败的话没有变更ok的值。会出现这样的结果。
![image](https://user-images.githubusercontent.com/13212775/188151925-41118dda-32a1-4aec-8452-28268e9c142c.png)
![image](https://user-images.githubusercontent.com/13212775/188151972-58cbdfd9-fc0f-43d3-95ab-36a2271ebdc7.png)
这个还会影响到测试计划的统计结果，断言失败的还是显示为成功。

**Comment by wuranxu** [comment]
已修复~
