### ISSUE TITLE
接口前置条件添加SQL语句，请求接口报错(AttributeError: 'list' object has no attribute 'keys')

### ISSUE THREAD

**Issue by jh11303** [wuranxu/pity#92]
## 问题描述
预置条件：已配置测试环境、已配置数据库设置。
1. 在编辑用例页面-前置条件中，添加SQL语句的前置步骤；
![image](https://user-images.githubusercontent.com/26341719/216966743-bf69f1cb-cd73-4b42-aed7-39e783581450.png)
2. 通过测试环境运行接口用例，执行日志中提示执行SQL失败。
![image](https://user-images.githubusercontent.com/26341719/216967284-997e0f51-59b9-492d-94c7-6948b509687c.png)
## 参考信息
![image](https://user-images.githubusercontent.com/26341719/216967635-9ff38dc4-94b8-4c96-a78c-cb1c4eb8f7e6.png)

**Comment by wuranxu** [comment]
已修复，感谢告知~
