### ISSUE TITLE
设置出参提取，请求接口报错(TypeError: parse() got an unexpected keyword argument 'index')

### ISSUE THREAD

**Issue by jh11303** [wuranxu/pity#93]
## 问题描述
预置条件：测试接口可正常返回Response。
1. 在编辑用例页面-出参提取中，配置Response-Header字段提取；
![4D8AC549-89AF-4aa5-98E4-BDEBF63D8430](https://user-images.githubusercontent.com/26341719/217045859-851c2827-3cd5-4af9-a959-f243d212dfcc.png)
2. 通过测试环境运行接口用例，出参提取报错。
![image](https://user-images.githubusercontent.com/26341719/217046233-e46ec8ef-b355-4cbf-85cf-58fb0cd3c747.png)

## 参考信息
![2A328638-1E2F-4355-A6AB-E5E66233D3AC](https://user-images.githubusercontent.com/26341719/217046266-54025ed5-7f60-4952-bf11-40005efb0093.png)

**Comment by jh11303** [comment]
目前页面的“第0个匹配项”对应的index为0

index入参默认减1会不会符合使用设计？（第1个匹配项对应的index为0）

![image](https://user-images.githubusercontent.com/26341719/217121789-5db2fdf0-27c9-4845-8f3e-ca8d8880529d.png)

**Comment by wuranxu** [comment]
> 目前页面的“第0个匹配项”对应的index为0
> 
> index入参默认减1会不会符合使用设计？（第1个匹配项对应的index为0）
> 
> ![image](https://user-images.githubusercontent.com/26341719/217121789-5db2fdf0-27c9-4845-8f3e-ca8d8880529d.png)

这里是支持负数的，改成-1不太方便，为了区分，前端的`第几个匹配项`会改为`索引`
