### ISSUE TITLE
/request/cert 报110

### ISSUE THREAD

**Issue by llaichiyu** [wuranxu/pity#94]
http://127.0.0.1:7777/request/cert?cert=2

{"code":110,"msg":"download file failed","data":null}

**Comment by wuranxu** [comment]
> http://127.0.0.1:7777/request/cert?cert=2
> 
> {"code":110,"msg":"download file failed","data":null}

代理服务关闭导致的，不算bug，你如果是本地使用的话请开启7778的代理服务
