### ISSUE TITLE
前置用例的前置脚本返回的变量，会覆盖主用例的变量

### ISSUE THREAD

**Issue by jh11303** [wuranxu/pity#95]
## 问题描述
预置条件：已有前置接口，前置接口有指定提取的变量。
1. 在主用例中，配置前置用例，并且有相关脚本返回值；
 ![image](https://user-images.githubusercontent.com/26341719/218009451-95e756a6-8300-4f7b-8151-a4157b82724f.png)
2. 前置用例中，有相同的前置脚本返回值；
![image](https://user-images.githubusercontent.com/26341719/218009392-d7e5ee7e-4b32-4448-ba01-b6261beb64a9.png)
3. 运行用例后，日志中，前置用例和主用例的变量都是使用的前置用例中的变量。
![image](https://user-images.githubusercontent.com/26341719/218009739-6b0c04f2-6f0e-4e87-bad4-05a234683269.png)
![image](https://user-images.githubusercontent.com/26341719/218009675-68cf2dc4-22ed-4843-bad1-ece841c38bb7.png)

## 参考信息
![image](https://user-images.githubusercontent.com/26341719/218010402-0a3113e0-4b83-4fa7-a77c-d58c015a6682.png)
![image](https://user-images.githubusercontent.com/26341719/218010615-cd020fe3-e07f-4eae-93bd-a5a6551179f9.png)
前置用例执行后，会用所有的变量对主用例进行参数替换，应该是用提取的变量进行替换就可以了吧？
（替换提取的变量+返回的变量？感觉有点奇怪。。）
（或者针对已存在变量，进行参数值更新是不是也可以？）

**Comment by wuranxu** [comment]
这里会重新设计，建议`暂时`不要用重名变量
