### ISSUE TITLE
能够自动化抓包生成关联依赖的上一个接口返回的json字段路径以及参数变量，并且能够自动生成关联参数变量传入到下一个接口，全部自动化实现，无效手动关联可以吗？

### ISSUE THREAD

**Issue by cfy3133** [wuranxu/pity#97]
![image](https://user-images.githubusercontent.com/43978367/226518936-fef91336-aec6-49e0-a1f7-cb7e9a00c86a.png)

**Comment by wuranxu** [comment]
用例录制里面有具体实现，可以`导入har`生成case

**Comment by cfy3133** [comment]
但是关联的参数还是要手动修改呢？能自动化实现吗？请问

**Comment by wuranxu** [comment]
> 但是关联的参数还是要手动修改呢？能自动化实现吗？请问

目前是自动化实现的呀，你可以导入一个har试试，不过目前有所调整，那块估计需要重新弄，但是会自动关联变量的，比如

**Comment by wuranxu** [comment]
> 但是关联的参数还是要手动修改呢？能自动化实现吗？请问

https://github.com/wuranxu/pity/blob/2f7d6d73b943e76dea37ac1ab73314e5a827cc8c/app/core/request/generator.py#L78

**Comment by cfy3133** [comment]
好的，谢谢您
