### ISSUE TITLE
pip 安装依赖出现版本错误

### ISSUE THREAD

**Issue by abeelan** [wuranxu/pity#98]
```bash
$ pip install -r requirements.txt -i http://pypi.douban.com/simple/
```
出现报错
> ERROR: Could not find a version that satisfies the requirement aioify~=0.4.1 (from versions: 0.1.3, 0.2.0, 0.3.1, 0.3.2, 0.4.0)
> ERROR: No matching distribution found for aioify~=0.4.1

```bash
# 官方源也出现该问题
$ pip install aioify~=0.4.1
```
修改 `requirements.txt` 中 `aioify~=0.4.0` 版本后，重新安装，执行成功。

**Comment by wuranxu** [comment]
> ```shell
> $ pip install -r requirements.txt -i http://pypi.douban.com/simple/
> ```
> 
> 出现报错
> 
> > ERROR: Could not find a version that satisfies the requirement aioify~=0.4.1 (from versions: 0.1.3, 0.2.0, 0.3.1, 0.3.2, 0.4.0)
> > ERROR: No matching distribution found for aioify~=0.4.1
> 
> ```shell
> # 官方源也出现该问题
> $ pip install aioify~=0.4.1
> ```
> 
> 修改 `requirements.txt` 中 `aioify~=0.4.0` 版本后，重新安装，执行成功。

好的，我这就修改一下
